import type { Patient } from './types'

// Test data for dashboard - using numbers and locations instead of patient names
export const testPatients: Patient[] = [
  {
    id: 'PT001',
    initials: '#001',
    location: 'ward',
    hasCompletedIntake: true,
    lastAssessment: '2025-12-19T08:30:00',
    recentMedications: ['Morphine 10mg', 'Paracetamol', 'Ibuprofen'],
    notes: 'Pain improving with current regimen. Continue morphine 10mg q4h. Monitor for breakthrough pain. Patient resting comfortably, alert and oriented. Next dose due at 12:30.',
    lastStaffName: 'Dr. Sarah',
    lastStaffRole: 'doctor',
    lastAction: 'Pain medication administered',
    lastActionTime: '2025-12-19T08:30:00',
    scheduledTime: '2025-12-19T10:00:00',
    currentPainLevel: 4
  },
  {
    id: 'PT002',
    initials: '#002',
    location: 'home',
    hasCompletedIntake: true,
    lastAssessment: '2025-12-19T07:15:00',
    recentMedications: ['Codeine', 'Amoxicillin'],
    notes: 'Sacral wound 4x3cm showing signs of infection - increased redness, moderate drainage. Dressing changed, wound cleaned. Started on Amoxicillin 500mg TID. Pain 7/10, given codeine. Caregiver educated on wound care. Check again tomorrow.',
    lastStaffName: 'Nurse Jane',
    lastStaffRole: 'nurse',
    lastAction: 'Wound dressing changed',
    lastActionTime: '2025-12-19T07:15:00',
    scheduledTime: '2025-12-19T14:00:00',
    currentPainLevel: 7
  },
  {
    id: 'PT003',
    initials: '#003',
    location: 'ward',
    hasCompletedIntake: true,
    lastAssessment: '2025-12-18T16:45:00',
    recentMedications: ['Diazepam', 'Omeprazole'],
    notes: 'Stable overnight. Vitals normal - BP 120/80, HR 72, temp 36.8C. Anxiety well controlled on diazepam 5mg BID. Eating small amounts, tolerating liquids well. No nausea. Continue current medications.',
    lastStaffName: 'Dr. John',
    lastStaffRole: 'doctor',
    lastAction: 'Vital signs checked',
    lastActionTime: '2025-12-18T16:45:00',
    currentPainLevel: 2
  },
  {
    id: 'PT004',
    initials: '#004',
    location: 'home',
    hasCompletedIntake: true,
    lastAssessment: '2025-12-19T09:00:00',
    recentMedications: ['Metformin', 'Aspirin', 'Atorvastatin'],
    notes: 'BP elevated at 145/92, will monitor closely. Blood sugar 8.2 mmol/L - good control. Minimal chest discomfort 3/10, no radiation. Taking all medications as prescribed. Encourage fluid intake and rest.',
    lastStaffName: 'Nurse Mary',
    lastStaffRole: 'nurse',
    lastAction: 'Blood pressure monitored',
    lastActionTime: '2025-12-19T09:00:00',
    scheduledTime: '2025-12-19T11:30:00',
    currentPainLevel: 3
  },
  {
    id: 'PT005',
    initials: '#005',
    location: 'ward',
    hasCompletedIntake: true,
    lastAssessment: '2025-12-19T06:00:00',
    recentMedications: ['Tramadol', 'Ondansetron'],
    notes: 'Pain poorly controlled at 8/10 despite tramadol. Discussed changing to stronger opioid. Nausea managed with ondansetron 4mg q8h. Patient unable to eat, taking sips of water only. Requires urgent medication review and pain reassessment.',
    lastStaffName: 'Dr. Sarah',
    lastStaffRole: 'doctor',
    lastAction: 'Medication review completed',
    lastActionTime: '2025-12-19T06:00:00',
    currentPainLevel: 8
  },
  {
    id: 'PT006',
    initials: '#006',
    location: 'home',
    hasCompletedIntake: true,
    lastAssessment: '2025-12-18T14:20:00',
    recentMedications: ['Furosemide', 'Digoxin'],
    notes: 'Mild ankle edema, improved from last week. Heart rate irregular at 68-78 bpm. Taking furosemide 40mg daily, digoxin 0.125mg daily. Discussed end-of-life wishes with family - advance directive completed. Follow-up needed to monitor fluid status.',
    lastStaffName: 'Nurse Peter',
    lastStaffRole: 'nurse',
    lastAction: 'Family counseling provided',
    lastActionTime: '2025-12-18T14:20:00',
    scheduledTime: '2025-12-19T15:30:00',
    currentPainLevel: 5
  },
  {
    id: 'PT007',
    initials: '#007',
    location: 'ward',
    hasCompletedIntake: true,
    lastAssessment: '2025-12-19T07:45:00',
    recentMedications: ['Insulin', 'Metoclopramide'],
    notes: 'Blood glucose 6.8 mmol/L - well controlled. On insulin sliding scale. No hypoglycemia episodes overnight. Minimal nausea, metoclopramide helping. Minimal pain. Continue monitoring glucose QID and adjust insulin as needed.',
    lastStaffName: 'Nurse Jane',
    lastStaffRole: 'nurse',
    lastAction: 'Glucose levels checked',
    lastActionTime: '2025-12-19T07:45:00',
    currentPainLevel: 1
  },
  {
    id: 'PT008',
    initials: '#008',
    location: 'home',
    hasCompletedIntake: true,
    lastAssessment: '2025-12-19T08:00:00',
    recentMedications: ['Ciprofloxacin', 'Prednisolone'],
    notes: 'UTI symptoms improving on ciprofloxacin 500mg BID day 3 of 7. Less dysuria, fever resolved. Started prednisolone taper for COPD exacerbation. Breathing easier but still short of breath on exertion. Pain 6/10 related to coughing. Monitor respiratory status.',
    lastStaffName: 'Dr. John',
    lastStaffRole: 'doctor',
    lastAction: 'Prescription updated',
    lastActionTime: '2025-12-19T08:00:00',
    scheduledTime: '2025-12-19T16:00:00',
    currentPainLevel: 6
  },
  {
    id: 'PT009',
    initials: '#009',
    location: 'ward',
    hasCompletedIntake: false,
    notes: 'New admission. Severe pain 9/10, appears distressed. Intake in progress - gathering medical history. Urgent pain management needed before completing full assessment. Await doctor for medication orders.',
    lastStaffName: 'Nurse Mary',
    lastStaffRole: 'nurse',
    lastAction: 'Initial intake started',
    lastActionTime: '2025-12-19T09:30:00',
    currentPainLevel: 9
  },
  {
    id: 'PT010',
    initials: '#010',
    location: 'home',
    hasCompletedIntake: true,
    lastAssessment: '2025-12-18T11:00:00',
    recentMedications: ['Lactulose', 'Docusate'],
    notes: 'Constipation ongoing - no bowel movement in 4 days despite lactulose and docusate. Abdominal discomfort 4/10. May need suppository or enema if no movement today. Increased fluid intake advised. Caregiver aware to call if worsening.',
    lastStaffName: 'Nurse Peter',
    lastStaffRole: 'nurse',
    lastAction: 'Bowel care provided',
    lastActionTime: '2025-12-18T11:00:00',
    currentPainLevel: 4
  }
]
